blueprint:
  name: Room Presence Sensor Combiner
  description: >
    Combine multiple presence sensors into a single virtual room sensor.
    When any sensor indicates presence, the room is considered occupied.
    When all sensors are inactive, the room is considered unoccupied.
  domain: automation
  input:
    room_name:
      name: Room Name
      description: Name of the room to represent in the virtual sensor.
      default: 'Room'
    presence_sensors:
      name: Presence Sensors
      description: List of presence sensors to monitor.
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    virtual_sensor:
      name: Virtual Room Sensor
      description: Input boolean to represent the room presence state.
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: state
    entity_id: !input presence_sensors

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {% for sensor in states | selectattr('entity_id', 'in', (blueprint.inputs.presence_sensors | list)) %}
                {% if sensor.state == 'on' %}
                  {{ true }}
                {% endif %}
              {% endfor %}
              {{ false }}
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input virtual_sensor
      - conditions:
          - condition: template
            value_template: >
              {% for sensor in states | selectattr('entity_id', 'in', (blueprint.inputs.presence_sensors | list)) %}
                {% if sensor.state == 'on' %}
                  {{ false }}
                {% endif %}
              {% endfor %}
              {{ true }}
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input virtual_sensor
